name: deploy to github pages

on:
  push:
    branches:
      - master

jobs:
  install:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

  lint:
    needs: [install]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn lint

  # test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: "**/node_modules"
  #         key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #         cache: 'yarn'
  #     - run: yarn install --frozen-lockfile
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #         cache: 'yarn'
  #     - run: yarn test --coverage

  deploy:
    name: deploy to github pages
    runs-on: ubuntu-latest
    # needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn build:parcel
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
